# Generated by Django 6.0.5 on 2026-05-26 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido_paterno', models.CharField(max_length=60)),
                ('apellido_materno', models.CharField(blank=True, max_length=60)),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('telefono_alt', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('calle', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('VER', 'Veracruz'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('CDMX', 'Ciudad de México'), ('JAL', 'Jalisco')], default='VER', max_length=4)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, null=True)),
                ('historial_productivo', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(blank=True, max_length=30)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('variedad', models.CharField(blank=True, choices=[('RRIM 600', 'RRIM 600'), ('GT-1', 'GT-1'), ('PB 260', 'PB 260'), ('IAN 873', 'IAN 873'), ('Otro', 'Otro')], max_length=20)),
                ('hectareas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('edad_anos', models.IntegerField(default=0)),
                ('densidad_arboles', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('produccion', 'En producción'), ('establecimiento', 'Establecimiento'), ('vivero', 'Vivero'), ('renovacion', 'Renovación'), ('abandonada', 'Abandonada')], default='produccion', max_length=20)),
                ('lat_centro', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lon_centro', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='productores.productor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
